import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Revolutionizing Quantitative Computing with AI - Moxie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-2 ${publicSans.className}`}>
        <div id="root" className="flex border-stroke border-[1px] rounded-lg">
          {children}
        </div>
      </body>
    </html>
  );
}
