import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./_contexts/AuthContext";
import { ModalProvider } from "./_contexts/ModalContext";
import Modal from "./_components/wrappers/Modal";
import { MotionConfig } from "framer-motion";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Revolutionizing Quantitative Computing with AI - Moxie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background ${publicSans.className}`}>
        {children}
      </body>
    </html>
  );
}
