const checkout_session_completed = {
  object: {
    id: "cs_test_a1k7CMMTd8RXYceRBXmf57ysvIfhcsilzI8Xa509EqYvv8IxTQIoAuGBxd",
    object: "checkout.session",
    adaptive_pricing: null,
    after_expiration: null,
    allow_promotion_codes: false,
    amount_subtotal: 11999,
    amount_total: 11999,
    automatic_tax: {
      enabled: false,
      liability: null,
      status: null,
    },
    billing_address_collection: "auto",
    cancel_url: "https://stripe.com",
    client_reference_id: null,
    client_secret: null,
    consent: null,
    consent_collection: {
      payment_method_reuse_agreement: null,
      promotions: "none",
      terms_of_service: "none",
    },
    created: 1736963569,
    currency: "usd",
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      after_submit: null,
      shipping_address: null,
      submit: null,
      terms_of_service_acceptance: null,
    },
    customer: "cus_RamLfljGo2YV2B",
    customer_creation: "if_required",
    customer_details: {
      address: {
        city: null,
        country: "BR",
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      email: "newuser@newuser.com",
      name: "Ricardo Rodrigues",
      phone: null,
      tax_exempt: "none",
      tax_ids: [],
    },
    customer_email: null,
    expires_at: 1737049969,
    invoice: "in_1Qhan9GC0DoVg5C52FDTtpTa",
    invoice_creation: null,
    livemode: false,
    locale: "auto",
    metadata: {},
    mode: "subscription",
    payment_intent: null,
    payment_link: "plink_1QOZ7MGC0DoVg5C5VNgIyukP",
    payment_method_collection: "always",
    payment_method_configuration_details: {
      id: "pmc_1QOZ3UGC0DoVg5C5ME4WuAUb",
      parent: null,
    },
    payment_method_options: {
      card: {
        request_three_d_secure: "automatic",
      },
    },
    payment_method_types: ["card"],
    payment_status: "paid",
    phone_number_collection: {
      enabled: false,
    },
    recovered_from: null,
    saved_payment_method_options: {
      allow_redisplay_filters: ["always"],
      payment_method_remove: null,
      payment_method_save: null,
    },
    setup_intent: null,
    shipping_address_collection: null,
    shipping_cost: null,
    shipping_details: null,
    shipping_options: [],
    status: "complete",
    submit_type: "auto",
    subscription: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    success_url: "https://stripe.com",
    tax_id_collection: {
      enabled: true,
      required: "never",
    },
    total_details: {
      amount_discount: 0,
      amount_shipping: 0,
      amount_tax: 0,
    },
    ui_mode: "hosted",
    url: null,
  },
};

const customer_subscription_created = {
  object: {
    id: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      disabled_reason: null,
      enabled: false,
      liability: null,
    },
    billing_cycle_anchor: 1736963651,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1736963651,
    currency: "usd",
    current_period_end: 1768499651,
    current_period_start: 1736963651,
    customer: "cus_RamLfljGo2YV2B",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    ended_at: null,
    invoice_settings: {
      account_tax_ids: null,
      issuer: {
        type: "self",
      },
    },
    items: {
      object: "list",
      data: [
        {
          id: "si_RamLjI3tLNyNUI",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1736963651,
          discounts: [],
          metadata: {},
          plan: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 11999,
            amount_decimal: "11999",
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            interval: "year",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            recurring: {
              aggregate_usage: null,
              interval: "year",
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 11999,
            unit_amount_decimal: "11999",
          },
          quantity: 1,
          subscription: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    },
    latest_invoice: "in_1Qhan9GC0DoVg5C52FDTtpTa",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          network: null,
          request_three_d_secure: "automatic",
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 11999,
      amount_decimal: "11999",
      billing_scheme: "per_unit",
      created: 1732428943,
      currency: "usd",
      interval: "year",
      interval_count: 1,
      livemode: false,
      metadata: {},
      meter: null,
      nickname: null,
      product: "prod_RH7LpwjDu6kgxi",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1736963651,
    status: "incomplete",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
};

const customer_subscription_updated = {
  object: {
    id: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      disabled_reason: null,
      enabled: false,
      liability: null,
    },
    billing_cycle_anchor: 1736963651,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: "charge_automatically",
    created: 1736963651,
    currency: "usd",
    current_period_end: 1768499651,
    current_period_start: 1736963651,
    customer: "cus_RamLfljGo2YV2B",
    days_until_due: null,
    default_payment_method: "pm_1Qhan7GC0DoVg5C52CNYYead",
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    ended_at: null,
    invoice_settings: {
      account_tax_ids: null,
      issuer: {
        type: "self",
      },
    },
    items: {
      object: "list",
      data: [
        {
          id: "si_RamLjI3tLNyNUI",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1736963651,
          discounts: [],
          metadata: {},
          plan: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 11999,
            amount_decimal: "11999",
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            interval: "year",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            recurring: {
              aggregate_usage: null,
              interval: "year",
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 11999,
            unit_amount_decimal: "11999",
          },
          quantity: 1,
          subscription: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/subscription_items?subscription=sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    },
    latest_invoice: "in_1Qhan9GC0DoVg5C52FDTtpTa",
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          network: null,
          request_three_d_secure: "automatic",
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
      save_default_payment_method: "off",
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 11999,
      amount_decimal: "11999",
      billing_scheme: "per_unit",
      created: 1732428943,
      currency: "usd",
      interval: "year",
      interval_count: 1,
      livemode: false,
      metadata: {},
      meter: null,
      nickname: null,
      product: "prod_RH7LpwjDu6kgxi",
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed",
    },
    quantity: 1,
    schedule: null,
    start_date: 1736963651,
    status: "active",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: "create_invoice",
      },
    },
    trial_start: null,
  },
  previous_attributes: {
    default_payment_method: null,
    status: "incomplete",
  },
};

const invoice_payment_succeeded = {
  object: {
    id: "in_1Qhan9GC0DoVg5C52FDTtpTa",
    object: "invoice",
    account_country: "BR",
    account_name: "Moreovr",
    account_tax_ids: null,
    amount_due: 11999,
    amount_paid: 11999,
    amount_remaining: 0,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 1,
    attempted: true,
    auto_advance: false,
    automatic_tax: {
      disabled_reason: null,
      enabled: false,
      liability: null,
      status: null,
    },
    automatically_finalizes_at: null,
    billing_reason: "subscription_create",
    charge: "ch_3Qhan9GC0DoVg5C51ONwzEbT",
    collection_method: "charge_automatically",
    created: 1736963651,
    currency: "usd",
    custom_fields: null,
    customer: "cus_RamLfljGo2YV2B",
    customer_address: {
      city: null,
      country: "BR",
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    customer_email: "newuser@newuser.com",
    customer_name: "Ricardo Rodrigues",
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: "none",
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    due_date: null,
    effective_at: 1736963651,
    ending_balance: 0,
    footer: null,
    from_invoice: null,
    hosted_invoice_url:
      "https://invoice.stripe.com/i/acct_1QOWW3GC0DoVg5C5/test_YWNjdF8xUU9XVzNHQzBEb1ZnNUM1LF9SYW1MY1hpbUdwZW1BbXFOT3YzUTlneTF3Tm5xMThhLDEyNzUwNDQ1NA0200XU7V3PlK?s=ap",
    invoice_pdf:
      "https://pay.stripe.com/invoice/acct_1QOWW3GC0DoVg5C5/test_YWNjdF8xUU9XVzNHQzBEb1ZnNUM1LF9SYW1MY1hpbUdwZW1BbXFOT3YzUTlneTF3Tm5xMThhLDEyNzUwNDQ1NA0200XU7V3PlK/pdf?s=ap",
    issuer: {
      type: "self",
    },
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: "list",
      data: [
        {
          id: "il_1Qhan9GC0DoVg5C5XJWKWPNd",
          object: "line_item",
          amount: 11999,
          amount_excluding_tax: 11999,
          currency: "usd",
          description: "1 × Teste anual (at $119.99 / year)",
          discount_amounts: [],
          discountable: true,
          discounts: [],
          invoice: "in_1Qhan9GC0DoVg5C52FDTtpTa",
          livemode: false,
          metadata: {},
          period: {
            end: 1768499651,
            start: 1736963651,
          },
          plan: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 11999,
            amount_decimal: "11999",
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            interval: "year",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          pretax_credit_amounts: [],
          price: {
            id: "price_1QOZ6hGC0DoVg5C5Nroij53A",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1732428943,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_RH7LpwjDu6kgxi",
            recurring: {
              aggregate_usage: null,
              interval: "year",
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 11999,
            unit_amount_decimal: "11999",
          },
          proration: false,
          proration_details: {
            credited_items: null,
          },
          quantity: 1,
          subscription: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
          subscription_item: "si_RamLjI3tLNyNUI",
          tax_amounts: [],
          tax_rates: [],
          type: "subscription",
          unit_amount_excluding_tax: "11999",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/invoices/in_1Qhan9GC0DoVg5C52FDTtpTa/lines",
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: "B0185448-0001",
    on_behalf_of: null,
    paid: true,
    paid_out_of_band: false,
    payment_intent: "pi_3Qhan9GC0DoVg5C51Z0SEO3x",
    payment_settings: {
      default_mandate: null,
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          request_three_d_secure: "automatic",
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
    },
    period_end: 1736963651,
    period_start: 1736963651,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: "paid",
    status_transitions: {
      finalized_at: 1736963651,
      marked_uncollectible_at: null,
      paid_at: 1736963652,
      voided_at: null,
    },
    subscription: "sub_1Qhan9GC0DoVg5C5Un3mpJtm",
    subscription_details: {
      metadata: {},
    },
    subtotal: 11999,
    subtotal_excluding_tax: 11999,
    tax: null,
    test_clock: null,
    total: 11999,
    total_discount_amounts: [],
    total_excluding_tax: 11999,
    total_pretax_credit_amounts: [],
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: null,
  },
};
